name: End-to-end tests
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  e2e-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Allow ptrace
        run: sudo sysctl -w kernel.yama.ptrace_scope=0
      - name: Run Docker e2e test
        run: make test-e2e-docker

  e2e-k3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Allow ptrace
        run: sudo sysctl -w kernel.yama.ptrace_scope=0
      - name: Install k3d
        # renovate: datasource=github-releases depName=k3d-io/k3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.8.3 bash
      - name: Run k3d e2e test
        run: make test-e2e-k3d
